/*
 * cosmos_wrapper.c - Wrapper to compile scx_cosmos as userspace C
 *
 * This file includes the simulator wrapper infrastructure and then
 * the actual scheduler source. The header guards in common.bpf.h
 * prevent re-inclusion, so our overridden macros take effect.
 *
 * NOTE: This file is compiled with -Dconst= to strip const qualifiers.
 * BPF schedulers declare globals as "const volatile" (patched by the
 * BPF loader). Stripping const makes them writable from Rust.
 */
#include "sim_wrapper.h"
#include "sim_task.h"

/* Simulator CPU count; sizes the per-CPU map registration (SCX_REGISTER_PERCPU). */
#define MAX_SIM_CPUS 128

/*
 * Simulated PMU kfunc stubs.
 *
 * The new COSMOS API uses scx_pmu_read() kfunc instead of the old
 * start_readings map + bpf_perf_event_read_value() approach.
 *
 * We simulate PMU counters using scx_bpf_now() as a monotonic counter.
 * The delta between event_start and event_stop represents task runtime
 * in nanoseconds, which serves as a simulated "event count".
 *
 * Tasks with runtime > perf_threshold are classified as "event heavy"
 * and routed to the least-busy-event CPU.
 */
extern u64 scx_bpf_now(void);

/* Per-task PMU baseline storage (indexed by task pointer hash) */
#define PMU_TASK_HASH_SIZE 1024
static u64 pmu_task_baseline[PMU_TASK_HASH_SIZE];

static inline unsigned int pmu_task_hash(struct task_struct *p)
{
	return ((unsigned long)p >> 4) % PMU_TASK_HASH_SIZE;
}

/*
 * scx_pmu_install - Install a PMU event for tracking.
 * In simulation, this is a no-op since we use scx_bpf_now() as counter.
 */
int scx_pmu_install(u64 event)
{
	(void)event;
	return 0;
}

/*
 * scx_pmu_uninstall - Uninstall a PMU event.
 * No-op in simulation.
 */
int scx_pmu_uninstall(u64 event)
{
	(void)event;
	return 0;
}

/*
 * scx_pmu_task_init - Initialize per-task PMU tracking.
 * No-op in simulation.
 */
int scx_pmu_task_init(struct task_struct *p)
{
	(void)p;
	return 0;
}

/*
 * scx_pmu_task_fini - Finalize per-task PMU tracking.
 * No-op in simulation.
 */
int scx_pmu_task_fini(struct task_struct *p)
{
	(void)p;
	return 0;
}

/*
 * scx_pmu_event_start - Record baseline counter when task starts running.
 * Stores current scx_bpf_now() value as baseline.
 */
int scx_pmu_event_start(struct task_struct *p, bool update)
{
	(void)update;
	pmu_task_baseline[pmu_task_hash(p)] = scx_bpf_now();
	return 0;
}

/*
 * scx_pmu_event_stop - Mark end of PMU event tracking for task.
 * The actual reading happens in scx_pmu_read().
 */
int scx_pmu_event_stop(struct task_struct *p)
{
	(void)p;
	return 0;
}

/*
 * scx_pmu_read - Read PMU counter delta for a task.
 *
 * Returns the difference between current time and baseline (task runtime).
 * If clear=true, resets the baseline for the next measurement.
 */
int scx_pmu_read(struct task_struct *p, u64 event, u64 *value, bool clear)
{
	unsigned int hash = pmu_task_hash(p);
	u64 now = scx_bpf_now();
	u64 baseline = pmu_task_baseline[hash];

	(void)event;

	/* Return delta since event_start */
	if (now >= baseline)
		*value = now - baseline;
	else
		*value = 0;

	if (clear)
		pmu_task_baseline[hash] = now;

	return 0;
}

/*
 * bpf_map_lookup_elem override: route COSMOS map lookups to the test-map
 * registry (the simulator's stand-in for kernel BPF maps).
 */
static void *cosmos_map_lookup(void *map, const void *key)
{
	return scx_test_map_lookup_elem(map, key);
}
#undef bpf_map_lookup_elem
#define bpf_map_lookup_elem(map, key) cosmos_map_lookup((void *)(map), key)

/*
 * Include COSMOS interface header, then the scheduler source.
 * common.bpf.h is already included (header guard set), so our
 * BPF_STRUCT_OPS and SCX_OPS_DEFINE overrides are in effect.
 *
 * We include a patched copy of main.bpf.c (generated by config.mk)
 * that guards against division-by-zero in update_freq(). BPF
 * division-by-zero returns 0; native C crashes with SIGFPE.
 */
#include "intf.h"
#include "cosmos_main_patched.c"

/*
 * scx_bpf_cpu_node(): map a CPU to its NUMA node id.
 *
 * Upstream sched-ext/scx 36d589bb ("scx_cosmos: Enable full built-in
 * NUMA-aware idle CPU selection") introduced calls to scx_bpf_cpu_node()
 * behind __COMPAT_scx_bpf_cpu_node(). That COMPAT macro calls the kfunc when
 * bpf_ksym_exists(scx_bpf_cpu_node) holds; because this wrapper defines
 * scx_bpf_cpu_node (below), libbpf's !!sym is true, so the macro calls it — the
 * simulator must provide it (this function), or the call would jump through a
 * NULL weak __ksym symbol and SIGSEGV (test_numa_topology).
 *
 * Resolve the node from the wrapper's cpu_node_map (populated by
 * cosmos_configure_numa()); fall back to node 0 when the CPU is unmapped
 * (NUMA disabled, or a single-node topology). bpf_map_lookup_elem is the
 * cosmos_map_lookup override defined above, so this stays consistent with
 * the rest of the wrapper's map handling.
 */
s32 scx_bpf_cpu_node(s32 cpu)
{
	u32 key = (u32)cpu;
	u32 *node = bpf_map_lookup_elem(&cpu_node_map, &key);

	return node ? (s32)*node : 0;
}

/*
 * Register the COSMOS BPF maps with the test-map registry. task_ctx_stor
 * (TASK_STORAGE) and cpu_node_map (HASH) are create-on-demand; node_ctx_stor
 * (ARRAY) is kernel-preallocated, so it is pre-seeded with zeroed entries that
 * init_node() looks up during cosmos_init(); cpu_ctx_stor (PERCPU_ARRAY, one
 * entry per CPU) is likewise seeded.
 */
void cosmos_register_maps(void)
{
	scx_test_map_clear_all();

	SCX_REGISTER_STORAGE(task_ctx_stor);
	SCX_REGISTER_ARRAY(node_ctx_stor, true);
	SCX_REGISTER_ARRAY(cpu_node_map, false);
	SCX_REGISTER_PERCPU(cpu_ctx_stor, true);
}

/*
 * Combined setup function called from Rust before cosmos_init().
 * Registers maps and enables CPU 0 in the primary domain; the config globals are
 * written before run by the manifest apply_rodata path (scheduler_manifest.rs
 * cosmos.runtime.rodata), not here. num_cpus is unused (cosmos has no
 * CPU-count-derived rodata) but kept for the generic {prefix}_setup signature.
 */
void cosmos_setup(unsigned int num_cpus)
{
	struct cpu_arg arg = { .cpu_id = 0 };

	(void)num_cpus;

	cosmos_register_maps();
	enable_primary_cpu(&arg);
}

/*
 * Configure NUMA topology after setup.
 * Populates cpu_node_map with sequential grouping:
 * CPUs [0, cpus_per_node) → node 0, etc.
 * Enables NUMA-aware scheduling in COSMOS.
 */
void cosmos_configure_numa(unsigned int num_cpus, unsigned int nr_nodes)
{
	unsigned int cpus_per_node, cpu, node;

	if (nr_nodes <= 1)
		return;  /* leave numa_enabled=false */

	cpus_per_node = num_cpus / nr_nodes;
	for (cpu = 0; cpu < num_cpus; cpu++) {
		node = cpu / cpus_per_node;
		if (node >= nr_nodes)
			node = nr_nodes - 1;
		bpf_map_update_elem(&cpu_node_map, &cpu, &node, 0);
	}

	numa_enabled = true;
	nr_node_ids = nr_nodes;
}
