name: schtest

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  check_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            schtest/rust/target/
          key: ${{ runner.os }}-schtest-${{ hashFiles('schtest/rust/Cargo.lock') }}

      - name: Clippy check
        working-directory: schtest/rust
        run: cargo clippy -- -D warnings

      - name: Build
        working-directory: schtest/rust
        run: cargo build --release

      - name: Test
        working-directory: schtest/rust
        run: cargo test -- --skip test_process_iterations
